document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("	  <title>HHDC</title>");
document.writeln("	  <link rel=\'shortcut icon\' href=\'pics/DC_Logo.png\'>");
document.writeln("		<meta charset=\'utf-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'>");
document.writeln("	  <link rel=\'stylesheet\' href=\'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\'>");
document.writeln("	  <script src=\'https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\'></script>");
document.writeln("	  <script src=\'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\'></script>");
document.writeln("	  <style type=\'text/css\'>");
document.writeln("        html, body {width:100%;height:100%;} ");
document.writeln("        .my-navbar a{background:transparent !important;color:black !important}");
document.writeln("        .my-navbar a:hover {color:red !important;background:red;outline:0}");
document.writeln("				.my-navbar a:active {color:red;}");
document.writeln("        .my-navbar a {transition: color 0.2s ease-in-out;}");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<!-- The navigation -->");
document.writeln("		<nav class=\'navbar navbar-static-top my-navbar\' role=\'navigation\'>");
document.writeln("		  <div class=\'container-fluid\'>");
document.writeln("		    <div class=\'navbar-header\'>");
document.writeln("		      <a class=\'navbar-brand\' href=\'#\'>HHDC</a>");
document.writeln("		    </div>");
document.writeln("		    <ul class=\'nav navbar-nav\'>");
document.writeln("		      <li><a href=\'index.html\' target=\'publicHead\'><i class=\'glyphicon glyphicon-info-sign\'></i><b> About</b></a></li>");
document.writeln("			    <li><a href=\'Rules.html\' target=\'publicHead\'><i class=\'glyphicon glyphicon-th-list\'></i><b> Rules</b></a></li>");
document.writeln("		      <li><a href=\'Project.html\' target=\'publicHead\'><i class=\'glyphicon glyphicon-folder-open\'></i><b> Project</b></a></li>");
document.writeln("		      <li><a href=\'Sponsors.html\' target=\'publicHead\'><i class=\'glyphicon glyphicon-user\'></i><b> Sponsors</b></a></li>");
document.writeln("			    <li><a href=\'Join.html\' target=\'publicHead\'><b> Join</b></a></li>");
document.writeln("			    <li><a href=\'https://docs.qq.com/sheet/DUkhXakJ0VlRVSHZw?opendocxfrom=admin&tab=BB08J2\' target=\'navBar\'><b>Finance</b></a></li>");
document.writeln("		    </ul>");
document.writeln("		  </div>");
document.writeln("		</nav>");
document.writeln("		");
document.writeln("		<header class=\'jumbotron\'>");
document.writeln("      <div class=\'container\'>");
document.writeln("        <div class=\'row row-header\'>");
document.writeln("          <div class=\'col-xs-12 col-sm-3\'>");
document.writeln("            <img src=\'pics/Full_Logo.png\' width=\'60%\'>");
document.writeln("          </div>");
document.writeln("          <div class=\'col-xs-12 col-sm-6\'>");
document.writeln("            <p><b>杭州高中生开发者联盟HHDC</b></p>");
document.writeln("            <p><em>Coding & Cooperation</em></p>");
document.writeln("          </div>               ");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </header>");
document.writeln("		");
document.writeln("    <!-- jQuery (necessary for Bootstrap\'s JavaScript plugins) -->");
document.writeln("    <script src=\'https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\'></script>");
document.writeln("    <!-- Include all compiled plugins (below), or include individual files as needed -->");
document.writeln("    <script src=\'js/bootstrap.min.js\'></script>");
document.writeln("		");
document.writeln("</body>");
document.writeln("</html>");